services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_project_name.wsgi
    envVars:
      - key: SECRET_KEY
        value: your_secret_key_here
      - key: DATABASE_URL
        value: your_database_url_here
