# Generated by Django 5.1 on 2024-09-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_alter_pants_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='size',
            field=models.CharField(max_length=399),
        ),
        migrations.AlterField(
            model_name='sneakers',
            name='size',
            field=models.CharField(max_length=399),
        ),
    ]
