# Generated by Django 5.1 on 2024-09-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_allproducts_clothes_advertise_watches_advertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=277)),
                ('email', models.CharField(max_length=577)),
                ('passwords', models.CharField(max_length=577)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=277)),
            ],
        ),
    ]
