# Generated by Django 5.1 on 2024-09-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pants',
            name='advertise',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sneakers',
            name='advertise',
            field=models.TextField(default=''),
        ),
    ]
