# Generated by Django 5.1 on 2024-09-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_pants_advertise_sneakers_advertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.CharField(max_length=20),
        ),
    ]
