# Generated by Django 5.1 on 2024-09-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_alter_userinfo_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='age',
            new_name='birth_date',
        ),
    ]
