# Generated by Django 5.1 on 2024-09-18 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0011_alter_allproducts_discount_alter_clothes_discount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllProducts',
        ),
    ]
