# Generated by Django 5.1 on 2024-09-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0013_alter_clothes_discount_alter_pants_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='passwords',
            field=models.CharField(max_length=128),
        ),
    ]
