# Generated by Django 5.1 on 2024-09-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0014_alter_userinfo_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
