# Generated by Django 5.1 on 2024-09-30 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0015_userinfo_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_name',
            new_name='user',
        ),
    ]
