# Generated by Django 5.1 on 2024-09-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0017_alter_userinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.CharField(max_length=299),
        ),
    ]
