# Generated by Django 5.1.2 on 2024-10-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0022_cart_products_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='products',
        ),
        migrations.RemoveField(
            model_name='products',
            name='clothes',
        ),
        migrations.RemoveField(
            model_name='products',
            name='pants',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sneakers',
        ),
        migrations.RemoveField(
            model_name='products',
            name='watches',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
        migrations.DeleteModel(
            name='Clothes',
        ),
        migrations.DeleteModel(
            name='Pants',
        ),
        migrations.DeleteModel(
            name='Sneakers',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Watches',
        ),
    ]
