# Generated by Django 5.1.2 on 2024-10-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0026_products_cart_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='products',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
