# Generated by Django 5.1.2 on 2024-10-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0028_products_cart_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_url',
            field=models.FileField(upload_to='media/images'),
        ),
    ]
