# Generated by Django 5.1.2 on 2024-10-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0029_alter_products_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_url',
            field=models.FileField(upload_to='images'),
        ),
    ]
